"""
CSV Export

Generates a downloadable CSV of scored users.
"""

import io
import pandas as pd
import streamlit as st


def generate_csv_export():
    """
    Generate downloadable CSV of all users with
    their loyalty scores, tiers, and features.

    Returns bytes that st.download_button can serve.
    io.BytesIO creates an in-memory file â€” no disk needed.
    """
    scored = st.session_state.get('scored_df')
    if scored is None:
        return None

    export_df = scored.copy()

    # Add human-readable tier labels
    # pd.cut divides continuous scores into named buckets
    export_df['loyalty_tier'] = pd.cut(
        export_df['loyalty_score'],
        bins=[0, 25, 50, 75, 90, 100],
        labels=[
            'Casual', 'Active', 'Engaged',
            'Loyal', 'Power User'
        ],
        include_lowest=True
    )

    # Add power user flag
    power_ids = st.session_state.get('power_user_ids', set())
    export_df['is_power_user'] = (
        export_df['user_id'].isin(power_ids)
    ).astype(int)

    # Select and rename columns for clean export
    export_cols = {
        'user_id': 'Customer ID',
        'loyalty_score': 'Loyalty Score (0-100)',
        'loyalty_tier': 'Loyalty Tier',
        'is_power_user': 'Is Power User (1=Yes)',
        'total_orders': 'Total Orders',
        'avg_days_between_orders': 'Avg Days Between Orders',
        'reorder_rate': 'Reorder Rate',
        'dept_diversity': 'Departments Shopped',
        'avg_basket_size': 'Avg Basket Size',
        'total_items': 'Total Items Purchased'
    }

    final = export_df[list(export_cols.keys())].rename(
        columns=export_cols
    )

    # Convert to CSV bytes
    # io.StringIO is an in-memory string buffer
    # .encode('utf-8') converts string to bytes
    # Streamlit's download_button needs bytes
    buffer = io.StringIO()
    final.to_csv(buffer, index=False)
    return buffer.getvalue().encode('utf-8')
"""
Report Export

Generates a markdown text summary of the analysis findings.
"""

from datetime import datetime
import streamlit as st


def generate_summary_report():
    """
    Generate a text summary report of the analysis.
    Returns markdown string.
    """
    scored = st.session_state.get('scored_df')
    power = st.session_state.get('power')
    regular = st.session_state.get('regular')
    thresholds = st.session_state.get('thresholds_df')

    if scored is None:
        return "No analysis run yet."

    now = datetime.now().strftime("%B %d, %Y at %H:%M")

    report = f"""# Customer Loyalty Intelligence Report
**Generated:** {now}
**Dataset:** Instacart Grocery Platform

---

## Executive Summary

- **Total Customers Analyzed:** {len(scored):,}
- **Power Users Identified:** {len(power):,} ({len(power)/len(scored)*100:.1f}% of base)
- **Average Loyalty Score:** {scored['loyalty_score'].mean():.1f}/100
- **Score Threshold for Power Users:** {st.session_state.get('cutoff', 0):.1f}/100

---

## Power User Profile

Power users are the top {st.session_state.get('top_pct', 10)}% of customers by loyalty score.

| Metric | Power Users | Regular Users | Ratio |
|--------|-------------|---------------|-------|
"""

    if thresholds is not None:
        for _, row in thresholds.iterrows():
            report += (
                f"| {row['Feature']} | "
                f"{row['Power User Avg']} | "
                f"{row['Regular User Avg']} | "
                f"{row['Ratio']}x |\n"
            )

    report += """
---

## Key Findings

"""
    if thresholds is not None:
        top_3 = thresholds.head(3)
        for i, (_, row) in enumerate(top_3.iterrows(), 1):
            report += (
                f"{i}. **{row['Feature']}** is the "
                f"#{i} differentiator â€” power users have "
                f"**{row['Ratio']}x more** "
                f"({row['Power User Avg']} vs "
                f"{row['Regular User Avg']})\n\n"
            )

    report += """---

## Recommended Interventions

1. **Drive Repeat Purchases** â€” Target users with < 5 orders 
   with Day-7 reorder reminders
   
2. **Build Reorder Habits** â€” Send weekly "your favorites" 
   reminders to users with < 50% reorder rate
   
3. **Expand Category Exploration** â€” Cross-category offer 
   after 3rd order for users in < 5 departments

---

*Generated by Customer Loyalty Intelligence Agent*
"""
    return report
